# Error handling, "try...catch"

## It works like this:

## First, the code in try {...} is executed.

## If there were no errors, then catch (err) is ignored: the execution reaches the end of try and goes on, skipping catch.

## If an error occurs, then the try execution is stopped, and control flows to the beginning of catch (err). The err variable (we can use any name for it) will contain an error object with details about what happened.

##

##

##

##

##

##

##

##

##

##

##

##

##

##
